import type {
  Attachment,
  AttachmentAdapter,
  CompleteAttachment,
  PendingAttachment,
} from "@assistant-ui/react";
import type { ConvexReactClient } from "convex/react";
import { api } from "./convexApi";

// Attachment adapter for assistant-ui that uploads files straight into Convex
// file storage via a short-lived signed upload URL, then carries the resulting
// `_storage` id so `api.send.sendMessage` can attach it to the outbox row.
//
// Flow (Convex file upload pattern):
//   1) mutation api.send.generateUploadUrl  -> uploadUrl
//   2) POST the raw bytes to uploadUrl       -> { storageId }
//   3) keep storageId on attachment          -> read by onNew/sendMessage
//
// The browser never sees a server filesystem path; it only ever holds an opaque
// Convex storage id and a temporary signed URL. The upload URL is generated by
// an authenticated Convex mutation, so only the signed-in user can upload.

const MAX_BYTES = 25 * 1024 * 1024; // 25 MB client-side guard

/** Convex storage metadata stashed on the assistant-ui attachment. */
export interface ConvexAttachmentContent {
  storageId: string;
  filename: string;
  mimeType: string;
}

/** assistant-ui Attachment carrying our Convex storage id. */
export type ConvexAttachment = CompleteAttachment & {
  convex: ConvexAttachmentContent;
};

function makeId(): string {
  return `att_${Math.random().toString(36).slice(2)}_${Date.now()}`;
}

/**
 * Pull the Convex storage ids out of a turn's attachments so `onNew` can pass
 * them to `api.send.sendMessage({ attachmentIds })`.
 */
export function attachmentStorageIds(
  attachments: readonly Attachment[] | undefined,
): string[] {
  if (!attachments) return [];
  const ids: string[] = [];
  for (const a of attachments) {
    const convex = (a as Partial<ConvexAttachment>).convex;
    if (convex?.storageId) ids.push(convex.storageId);
  }
  return ids;
}

export function createConvexAttachmentAdapter(
  convex: ConvexReactClient,
): AttachmentAdapter {
  return {
    // Accept everything the bridge/OpenClaw can ingest; tighten per deployment.
    accept: "image/*,audio/*,video/*,text/*,application/pdf",

    async add({ file }: { file: File }): Promise<PendingAttachment> {
      if (file.size > MAX_BYTES) {
        throw new Error(
          `File too large (${Math.round(file.size / 1024 / 1024)} MB, max 25 MB).`,
        );
      }
      return {
        id: makeId(),
        type: inferAttachmentType(file.type),
        name: file.name,
        contentType: file.type || "application/octet-stream",
        file,
        status: { type: "running", reason: "uploading", progress: 0 },
      };
    },

    async send(attachment: PendingAttachment): Promise<CompleteAttachment> {
      const file = attachment.file;

      // 1) One-time signed upload URL from an authenticated mutation.
      const uploadUrl: string = await convex.mutation(
        api.send.generateUploadUrl,
        {},
      );

      // 2) Stream the bytes directly to Convex storage.
      const res = await fetch(uploadUrl, {
        method: "POST",
        headers: { "Content-Type": file.type || "application/octet-stream" },
        body: file,
      });
      if (!res.ok) {
        throw new Error(`Upload failed (${res.status})`);
      }
      const { storageId } = (await res.json()) as { storageId: string };

      const result: ConvexAttachment = {
        id: attachment.id,
        type: attachment.type,
        name: attachment.name,
        contentType: attachment.contentType,
        status: { type: "complete" },
        content: [{ type: "text", text: file.name }],
        convex: {
          storageId,
          filename: file.name,
          mimeType: file.type || "application/octet-stream",
        },
      };
      return result;
    },

    async remove(): Promise<void> {
      // Pending uploads are discarded client-side; orphaned storage rows are
      // garbage-collected by a Convex cron on the server (the browser lacks the
      // service key and must never delete storage directly).
    },
  };
}

function inferAttachmentType(mime: string): PendingAttachment["type"] {
  if (mime.startsWith("image/")) return "image";
  return "document";
}
